# Generated by Django 5.2.7 on 2025-10-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tenant_post_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
